### PR TITLE
Incorporate ClassLoaderFixer

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
Did neither notice any issues without nor with this change. So, this will definetly not hurt since it is a fundamental flaw to not set the `CodeSource` correctly :)

### CODE REVIEW

**Comment by ThexXTURBOXx** [comment]
Something else I have noticed btw: Coremods do not seem to work yet. Just to let you know :)

**Comment by thecatcore** [comment]
does it work in production?

**Comment by thecatcore** [comment]
yes I haven't handled coremods yet.

**Comment by ThexXTURBOXx** [comment]
> does it work in production?

Yes, it works flawlessly

> yes I haven't handled coremods yet.

Ah okay, that explains it :)

**Comment by thecatcore** [comment]
awesome, gonna merge it then :smile:

**Pull request merged**
